language: java

script:
- mvn compile
- mvn test
- mvn package
- mvn verify

deploy:
  provider: heroku
  api_key:
    secure: 6302276d-3cdb-4696-a0bf-dcb8c59a3adb
  app: salimAl
  edge:
    branch: heroku

branches:
  only:
    - master




